@Library('shared-libs') _
platformImageCI(
  agentLabel: "agent",
  dockerfile: "java/Dockerfile",
  imageName: "java-platform",
  imageTag: "17-jre-alpine-v1.0.0",
  ecrRepo: "384570460482.dkr.ecr.ap-south-1.amazonaws.com/platform/java-runtime",
  awsRegion: "ap-south-1"
)