@Library('shared-libs') _
platformImageCI(
  agentLabel: "agent",
  dockerfile: "nginx/Dockerfile",
  imageName: "nginx-platform",
  imageTag: "alpine-v1.0.0",
  ecrRepo: "384570460482.dkr.ecr.ap-south-1.amazonaws.com/platform/nginx",
  awsRegion: "ap-south-1"
)