@Library('shared-libs') _
platformImageCI(
  agentLabel: "agent",
  dockerfile: "python/Dockerfile",
  imageName: "python-platform",
  imageTag: "3.12-alpine-v1.0.0",
  ecrRepo: "384570460482.dkr.ecr.ap-south-1.amazonaws.com/platform/python-runtime",
  awsRegion: "ap-south-1"
)